def print_trade_good_scripted_guis(trade_goods):
	openbracket = "{" #hmm
	closebracket = "}"
	capital_word = trade_goods.replace("_", " ").title()
	scripted_guis = "set_{trade_goods}_focus = {openbracket}\n    scope = country\n    confirm_title = \"{trade_goods}_focus_title\"\n    confirm_text = \"{trade_goods}_focus_desc\"\n    ai_is_valid = {openbracket}\n        always = no\n    {closebracket}\n    is_valid = {openbracket}\n        trigger_if = {openbracket}\n            limit = {openbracket}\n                political_influence < 50\n            {closebracket}\n            political_influence >= 50\n        {closebracket}\n        trigger_if = {openbracket}\n            limit = {openbracket}\n                NOT = {openbracket}\n                    any_owned_province = {openbracket}\n                        trade_goods = {trade_goods}\n                    {closebracket}\n                {closebracket}\n            {closebracket}\n            any_owned_province = {openbracket}\n                trade_goods = {trade_goods}\n            {closebracket}\n        {closebracket}\n        trigger_if = {openbracket}\n            limit = {openbracket}\n                has_variable = {trade_goods}_focus\n            {closebracket}\n            custom_tooltip = {openbracket}\n                text = this_is_already_the_trade_good_focus_tt\n                NOT = {openbracket} has_variable = {trade_goods}_focus {closebracket}\n            {closebracket}\n        {closebracket}\n    {closebracket}\n    effect = {openbracket}\n        remove_trade_good_focus_variables_effect = yes\n        set_variable = {trade_goods}_focus\n        add_political_influence = -50\n        custom_tooltip = all_{trade_goods}_provinces_gain\n        random_owned_province = {openbracket}\n            show_as_tooltip = {openbracket}\n                add_province_modifier = {openbracket}\n                    name = production_focus\n                    duration = -1\n                {closebracket}\n            {closebracket}\n        {closebracket}\n        hidden_effect = {openbracket}\n            every_owned_province = {openbracket}\n                limit = {openbracket}\n                    has_province_modifier = production_focus\n                {closebracket}\n                remove_province_modifier = production_focus\n            {closebracket}\n            every_owned_province = {openbracket}\n                limit = {openbracket} trade_goods = {trade_goods} {closebracket}\n                add_province_modifier = {openbracket}\n                    name = production_focus\n                    duration = -1\n                {closebracket}\n            {closebracket}\n        {closebracket}\n    {closebracket}\n{closebracket}".format(openbracket=openbracket,closebracket=closebracket,trade_goods=trade_goods,capital_word=capital_word)
	print(scripted_guis)

def print_trade_good_loc(trade_goods):
	capital_word = trade_goods.replace("_", " ").title()
	no_underscore = trade_goods.replace("_", " ")
	localization = "{trade_goods}_focus_title:0 \"Production of {capital_word}\"\n{trade_goods}_focus_desc:0 \"Are you sure you want to focus on the production of {no_underscore}?\"\n".format(no_underscore=no_underscore,trade_goods=trade_goods,capital_word=capital_word)
	print(localization)	

trade_goods = ["grain","salt","iron","horses","wine","wood","amber","stone","fish","spices","elephants","papyrus","cloth","wild_game","precious_metals","steppe_horses","cattle","earthware","dye","fur","olive","leather","base_metals","woad","marble","honey","incense","hemp","vegetables","gems","camel","glass","silk","dates","sugar","cedar","myrrh","cinnabar","lapis","jade","fruits","silphium"]

for i in trade_goods:
	print_trade_good_loc(i)